/**
 * CHUCK REPORT GENERATOR
 * Professional Markdown report from a completed session.
 */

import type { Session, Finding } from "./schema.js";

const ORDER: Finding["severity"][] = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];

export function generateReport(session: Session): string {
  const sorted = [...session.findings].sort((a, b) => ORDER.indexOf(a.severity) - ORDER.indexOf(b.severity));
  const counts = ORDER.map(s => `${s}: ${sorted.filter(f => f.severity === s).length}`).join(" | ");
  const dur = session.finishedAt
    ? msToHuman(new Date(session.finishedAt).getTime() - new Date(session.startedAt).getTime())
    : "incomplete";

  return `# Chuck Security Assessment Report

**Session ID:** \`${session.id}\`
**Task:** ${session.task}${session.target ? `\n**Target:** ${session.target}` : ""}
**Date:** ${new Date(session.startedAt).toUTCString()}
**Duration:** ${dur}
**Total Findings:** ${session.findings.length} (${counts})

---

## Executive Summary

${session.findings.length === 0
    ? "No findings were identified during this assessment."
    : `This assessment identified **${session.findings.length} finding(s)**.${sorted.filter(f => f.severity === "CRITICAL").length > 0 ? ` **${sorted.filter(f => f.severity === "CRITICAL").length} CRITICAL** issue(s) require immediate remediation.` : ""}`}

---

## Findings

${sorted.length === 0 ? "_No findings._" : sorted.map((f, i) => `### ${i + 1}. [${f.severity}] ${f.title}

| Field | Value |
|-------|-------|
| **Severity** | ${f.severity} |
| **Affected Component** | ${f.affectedComponent || "N/A"} |${f.cve ? `\n| **CVE** | ${f.cve} |` : ""}${f.cvss !== undefined ? `\n| **CVSS** | ${f.cvss} |` : ""}

**PoC:** \`\`\`\n${f.poc || "See audit log"}\n\`\`\`

**Remediation:** ${f.remediation || "Not provided"}`).join("\n\n---\n\n")}

---

## Agent Analysis

${session.finalAnswer}

---

## Audit Trail

- Log: \`sessions/${session.id}/audit.jsonl\`
- Hash: \`sessions/${session.id}/session.hash\`
${session.auditHash ? `- SHA256: \`${session.auditHash}\`` : ""}

---
*Generated by Chuck v0.3.0 — Authorized use only*
`;
}

function msToHuman(ms: number): string {
  const s = Math.floor(ms / 1000), m = Math.floor(s / 60), h = Math.floor(m / 60);
  return h > 0 ? `${h}h ${m % 60}m` : m > 0 ? `${m}m ${s % 60}s` : `${s}s`;
}
